openapi: 3.0.0
info:
  title: Twitter Clone - Tweet & Timeline Service
  version: 1.0.0
  description: API untuk membuat tweet dan melihat timeline.
servers:
  - url: http://localhost:5003/api/tweets
    description: Development Server

tags:
  - name: Tweets
    description: Operasi terkait Tweet dan Timeline

components:
  schemas:
    Tweet:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
          maxLength: 280
        userId:
          type: string
          format: uuid
        replyToTweetId:
          type: string
          format: uuid
          nullable: true
          description: ID dari tweet yang dibalas. Null jika bukan balasan.
        createdAt:
          type: string
          format: date-time
    TweetInput:
      type: object
      required: [content]
      properties:
        content:
          type: string
          maxLength: 280
          example: "Ini adalah tweet pertama saya!"
        replyToTweetId:
          type: string
          format: uuid
          nullable: true
          description: Sertakan ID ini jika tweet ini adalah sebuah balasan.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /timeline:
    get:
      summary: Mendapatkan timeline untuk pengguna terautentikasi
      tags: [Tweets]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Timeline berhasil diambil
        '401':
          description: Unauthorized

  /:
    post:
      summary: Membuat sebuah tweet baru atau sebuah balasan
      tags: [Tweets]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TweetInput'
      responses:
        '201':
          description: Tweet berhasil dibuat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '400':
          description: Input tidak valid
        '401':
          description: Unauthorized
  
  /{id}/replies:
    get:
      summary: Mendapatkan semua balasan untuk sebuah tweet
      tags: [Tweets]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Daftar balasan berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tweet'
        '404':
          description: Tweet utama tidak ditemukan

  /{id}:
    put:
      summary: Memperbarui sebuah tweet
      tags: [Tweets]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        description: Konten baru untuk tweet
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content:
                  type: string
                  example: "Ini adalah konten tweet yang sudah diedit."
      responses:
        '200':
          description: Tweet berhasil diperbarui
        '403':
          description: Akses ditolak
        '404':
          description: Tweet tidak ditemukan
    delete:
      summary: Menghapus sebuah tweet
      tags: [Tweets]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '204':
          description: Tweet berhasil dihapus
        '403':
          description: Akses ditolak
        '404':
          description: Tweet tidak ditemukan