openapi: 3.0.0
info:
  title: Twitter Clone - Notification Service API
  version: 1.0.0
  description: API untuk mengambil dan mengelola status notifikasi pengguna.
servers:
  - url: http://localhost:5000/api/notifications # URL via API Gateway
    description: Development Server

tags:
  - name: Notifications
    description: Operasi untuk melihat dan mengelola notifikasi

components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID unik notifikasi.
        userId:
          type: string
          format: uuid
          description: ID pengguna penerima notifikasi.
        message:
          type: string
          description: Isi pesan notifikasi yang dibaca pengguna.
          example: "John Doe mulai mengikuti Anda."
        link:
          type: string
          nullable: true
          description: URL yang bisa diklik, misal ke profil atau tweet.
          example: "/profile/123e4567-e89b-12d3-a456-426614174000"
        isRead:
          type: boolean
          description: Status apakah notifikasi sudah dibaca atau belum.
        createdAt:
          type: string
          format: date-time
          description: Waktu notifikasi dibuat.
    
    SuccessMessage:
      type: object
      properties:
        message:
          type: string
          example: "Semua notifikasi telah ditandai sebagai dibaca."

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /:
    get:
      summary: Mendapatkan daftar notifikasi untuk pengguna yang login
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Daftar notifikasi berhasil diambil.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '401':
          description: Unauthorized. Token tidak valid atau tidak ada.

  /read:
    patch:
      summary: Menandai semua notifikasi pengguna sebagai 'telah dibaca'
      tags: [Notifications]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Berhasil memperbarui status notifikasi.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '401':
          description: Unauthorized. Token tidak valid atau tidak ada.